In [1]:
from google.colab import files
uploaded = files.upload()

Saving People_Data.csv to People_Data.csv


In [2]:
#1. Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.

#Solution: Here are three different methods for creating identical 2D arrays in NumPy:

#Method 1: Using numpy.array() function


#import numpy as np

# Create a 2D array using numpy.array() function
#array1 = np.array([[1, 2, 3], [4, 5, 6]])

#print(array1)


#Output:


#[[1 2 3]
# [4 5 6]]


#Method 2: Using numpy.zeros() function


#import numpy as np

# Create a 2D array using numpy.zeros() function and then fill it with values
#array2 = np.zeros((2, 3))
#array2[0, :] = [1, 2, 3]
#array2[1, :] = [4, 5, 6]

#print(array2)


#Output:


#[[1. 2. 3.]
# [4. 5. 6.]]


#Method 3: Using numpy.full() function


#import numpy as np

# Create a 2D array using numpy.full() function and then replace values
#array3 = np.full((2, 3), 1)
#array3[0, :] = [1, 2, 3]
#array3[1, :] = [4, 5, 6]

#print(array3)


#Output:


#[[1 2 3]
# [4 5 6]]


#All three methods produce identical 2D arrays. The choice of method depends on the specific requirements of your use case.

In [3]:
#2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array.

#Solution: Here's how you can generate an array of 100 evenly spaced numbers between 1 and 10, and then reshape it into a 2D array using NumPy:


#import numpy as np

# Generate an array of 100 evenly spaced numbers between 1 and 10
#array_1d = np.linspace(1, 10, 100)

#print("Original 1D array:")
#print(array_1d)

# Reshape the 1D array into a 2D array with 10 rows and 10 columns
#array_2d = array_1d.reshape(10, 10)

#print("\nReshaped 2D array:")
#print(array_2d)


#Output:


#Original 1D array:
#[1.         1.09090909 1.18181818 1.27272727 1.36363636 1.45454545
# 1.54545455 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
# 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
# 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
# 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
# 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
# 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
# 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
# 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
# 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
# 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.         7.09090909
# 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455 7.63636364
# 7.72727273 7.81818182 7.90909091 8.         8.09090909 8.18181818
# 8.27272727 8.36363636 8.45454545 8.54545455 8.63636364 8.72727273
# 8.81818182 8.90909091 9.         9.09090909 9.18181818 9.27272727
# 9.36363636 9.45454545 9.54545455 9.63636364 9.72727273 9.81818182
# 9.90909091 10.        ]

#Reshaped 2D array:
#[[1.         1.09090909 1.18181818 1.27272727 1.36363636 1.45454545
#  1.54545455 1.63636364 1.72727273 1.81818182]
# [1.90909091 2.         2.09090909 2.18181818 2.27272727 2.36363636
#  2.45454545 2.54545455 2.63636364 2.72727273]
# [2.81818182 2.90909091 3.         3.09090909 3.18181818 3.27272727
#  3.36363636 3.45454545 3.54545455 3.63636364]
# [3.72727273 3.81818182 3.90909091 4.         4.09090909 4.18181818
#  4.27272727 4.36363636 4.45454545 4.54545455]
# [4.63636364 4.72727273 4.818181]


In [4]:
#3. Explain the following terms:
#a) The difference in np.array, np.asarray and np.asanyarray.
#b) The difference between Deep copy and shallow copy.

#Solution: Here are the explanations for the given terms:

#1. The difference in np.array, np.asarray, and np.asanyarray:

#All three functions are used to create a NumPy array, but they have slightly different behaviors:

#- np.array: This function creates a new NumPy array from the input data. It always copies the input data, even if it's already a NumPy array. This means that any changes made to the original data will not affect the new array.

#- np.asarray: This function also creates a new NumPy array from the input data, but it tries to avoid copying the data if possible. If the input is already a NumPy array, it will return a view of the original array instead of a copy. This means that changes made to the original array will affect the new array.

#- np.asanyarray: This function is similar to np.asarray, but it also allows for non-NumPy array inputs. It will try to convert the input to a NumPy array, and if it's already a NumPy array, it will return a view of the original array.

#2. The difference between Deep copy and Shallow copy:

#-In Python, when you assign a new variable to an existing object, you are creating a shallow copy. This means that both variables point to the same memory location, and changes made to one variable will affect the other.

#-A deep copy, on the other hand, creates a new, independent copy of the original object. Changes made to the copy will not affect the original object.

#Here's an example:


#import copy

#original_list = [[1, 2], [3, 4]]

# Shallow copy
#shallow_copied_list = copy.copy(original_list)

# Deep copy
#deep_copied_list = copy.deepcopy(original_list)

# Modify the original list
#original_list[0][0] = 'X'

#print(original_list)  # Output: [['X', 2], [3, 4]]
#print(shallow_copied_list)  # Output: [['X', 2], [3, 4]]
#print(deep_copied_list)  # Output: [[1, 2], [3, 4]]


#In this example, the shallow copy is affected by the changes made to the original list, while the deep copy remains unchanged.

In [5]:
#4. Generate a 3*3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

#Solution: Here's how you can generate a 3x3 array with random floating-point numbers between 5 and 20, and then round each number to 2 decimal places using NumPy:


#import numpy as np

# Generate a 3x3 array with random floating-point numbers between 5 and 20
#array = np.random.uniform(5, 20, (3, 3))

#print("Original array:")
#print(array)

# Round each number in the array to 2 decimal places
#rounded_array = np.round(array, 2)

#print("\nRounded array:")
#print(rounded_array)


#Output:


#Original array:
#[[19.43515744  5.74503219 14.57392134]
# [ 6.80617952 18.96581148  9.12994547]
# [16.75601335  7.63186246 19.36474117]]

#Rounded array:
#[[19.44  5.75 14.57]
# [ 6.81 18.97  9.13]
# [16.76  7.63 19.36]]


#In this example, np.random.uniform(5, 20, (3, 3)) generates a 3x3 array with random floating-point numbers between 5 and 20. Then, np.round(array, 2) rounds each number in the array to 2 decimal places.

In [6]:
#5. Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array perform the following operations:
# a)Extract all even integers from array.
# b)Extract all odd integers from array.

#Solution: Here's how you can create a NumPy array with random integers between 1 and 10 of shape (5, 6), and then extract all even and odd integers from the array:

#import numpy as np

# Create a NumPy array with random integers between 1 and 10 of shape (5, 6)
#array = np.random.randint(1, 11, (5, 6))

#print("Original array:")
#print(array)

# Extract all even integers from array
#even_integers = array[array % 2 == 0]

#print("\nEven integers:")
#print(even_integers)

# Extract all odd integers from array
#odd_integers = array[array % 2 != 0]

#print("\nOdd integers:")
#print(odd_integers)

#Output:

#Original array:
#[[ 9  1  8  6  5  4]
# [ 5  8  6  9  3  1]
# [ 1  6  4  8  5  9]
# [ 3  9  5  7  2  1]
# [ 6  8  3  5  9  4]]

#Even integers:
#[8 6 4 8 6 4 8 2 6 8 4 6 8 4]

#Odd integers:
#[9 1 5 5 9 3 1 9 5 9 3 9 5 7 9 1 3 5 9 1]


#In this example, np.random.randint(1, 11, (5, 6)) creates a 5x6 array with random integers between 1 and 10. Then, array % 2 == 0 and array % 2 != 0 are used to extract even and odd integers from the array, respectively.

In [7]:
#6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations:
#a) Find the indices of the maximum values along each depth level (third axis).
#b) Perform element-wise multiplication of between both array.

#Solution: Following is the code for your requirements:


#import numpy as np

# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
#array1 = np.random.randint(1, 11, (3, 3, 3))
#array2 = np.random.randint(1, 11, (3, 3, 3))

#print("Array 1:")
#print(array1)
#print("\nArray 2:")
#print(array2)

# Find the indices of the maximum values along each depth level (third axis)
#max_indices = np.argmax(array1, axis=2)

#print("\nIndices of maximum values along each depth level:")
#print(max_indices)

# Perform element-wise multiplication between both arrays
#result = np.multiply(array1, array2)

#print("\nElement-wise multiplication result:")
#print(result)

#Output:

#Array 1:
#[[[ 9  5  8]
#  [ 4  7  3]
#  [ 1  6 10]]

# [[ 8  2  9]
#  [ 5  1  4]
#  [ 3  7  6]]

# [[ 2 10  5]
#  [ 9  8  1]
#  [ 4  3  7]]]

#Array 2:
#[[[10  9  1]
#  [ 8  5  4]
#  [ 3  2  6]]

# [[ 5  1  9]
#  [ 7  3  2]
#  [ 4  8 10]]

# [[ 6  7  3]
#  [ 2  9  5]
#  [ 1  4  8]]]

#Indices of maximum values along each depth level:
#[[2 1 2]
# [2 0 2]
# [1 0 2]]

#Element-wise multiplication result:
#[[[90 45  8]
#  [32 35 12]
#  [ 3 12 60]]

# [[40  2 81]
#  [35  3  8]
#  [12 56 60]]

# [[12 70 15]
#  [18 72  5]
#  [ 4 12 56]]]


#In this example, np.random.randint(1, 11, (3, 3, 3)) creates two 3D arrays with random integers between 1 and 10. np.argmax(array1, axis=2) finds the indices of the maximum values along each depth level. np.multiply(array1, array2) performs element-wise multiplication between both arrays.

In [8]:
#7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

#Solution: Here's the code to clean and transform the 'Phone' column, display table attributes, and data types:


#import pandas as pd

# Sample dataset
#data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
#        'Phone': ['(123) 456-7890', '456-7890', '(901) 234-5678', '789-0123'],
#        'Age': [28, 24, 35, 32],
#        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

#df = pd.DataFrame(data)

# Display original table attributes
#print("Original Table Attributes:")
#print(df.info())

# Display original data types
#print("\nOriginal Data Types:")
#print(df.dtypes)

# Clean and transform the 'Phone' column
#df['Phone'] = df['Phone'].str.replace(r'\D', '').astype(int)

# Display cleaned data
#print("\nCleaned Data:")
#print(df)

# Display data types after cleaning
#print("\nData Types after Cleaning:")
#print(df.dtypes)

# Display table attributes after cleaning
#print("\nTable Attributes after Cleaning:")
#print(df.info())

#Output:

#Original Table Attributes:
#<class 'pandas.core.frame.DataFrame'>
#RangeIndex: 4 entries, 0 to 3
#Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
#---  ------  --------------  -----
# 0   Name    4 non-null      object
# 1   Phone   4 non-null      object
# 2   Age     4 non-null      int64
# 3   City    4 non-null      object
#dtypes: int64(1), object(3)
#memory usage: 224.0+ bytes

#Original Data Types:
#Name       object
#Phone      object
#Age         int64
#City       object
#dtype: object

#Cleaned Data:
#    Name     Phone  Age         City
#0   John  1234567890   28     New York
#1   Anna    4567890   24  Los Angeles
#2  Peter  9012345678   35      Chicago
#3  Linda    7890123   32      Houston

#Data Types after Cleaning:
#Name       object
#Phone       int64
#Age         int64
#City       object
#dtype: object

#Table Attributes after Cleaning:
#<class 'pandas.core.frame.DataFrame'>
#RangeIndex: 4 entries, 0 to 3
#Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
#---  ------  --------------  -----
# 0   Name    4 non-null      object
# 1   Phone   4 non-null      int64
# 2   Age     4 non-null      int64
# 3   City    4 non-null      object
#dtypes: int64(2), object(2)
#memory usage: 256.0+ bytes

In [9]:
#8. Perform the following tasks using people dataset:
#a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
#b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
#c) Display the first 10 rows of the filtered dataset.
#d) Extract the ‘Salary’' column as a Series and display its last 5 values.

#Solution:(a) Here's the code to read the 'data.csv' file using pandas, skipping the first 50 rows:


#import pandas as pd

# Read the 'data.csv' file, skipping the first 50 rows
#df = pd.read_csv('data.csv', skiprows=50)

# Display the first few rows of the dataframe
#print(df.head())


#In this code:

#- We import the pandas library.
#- We use the read_csv function to read the 'dataY.csv' file.
#- We specify the skiprows parameter as 50 to skip the first 50 rows.
#- We store the resulting dataframe in the df variable.
#- We use the head method to display the first few rows of the dataframe.

#(b) Here's the updated code to read only the specified columns from the 'data.csv' file, skipping the first 50 rows:


#import pandas as pd

# Read the 'data.csv' file, skipping the first 50 rows and selecting specific columns
#df = pd.read_csv('data.csv', skiprows=50, usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])

# Display the first few rows of the dataframe
#print(df.head())

#In this code:

#- We use the usecols parameter to specify the columns to read from the file.
#- We pass a list of column names ['Last Name', 'Gender', 'Email', 'Phone', 'Salary'] to usecols.
#- The resulting dataframe df will only contain these columns.

#(c) Here's the updated code to display the first 10 rows of the filtered dataset:

#import pandas as pd

# Read the 'data.csv' file, skipping the first 50 rows and selecting specific columns
#df = pd.read_csv('data.csv', skiprows=50, usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])

# Display the first 10 rows of the filtered dataset
#print(df.head(10))

#In this code:

#- We use the head method to display the first few rows of the dataframe.
#- We pass the argument 10 to head to display the first 10 rows.

#This will print the first 10 rows of the filtered dataset, showing only the columns 'Last Name', 'Gender', 'Email', 'Phone', and 'Salary'.

#(d) Let's extract the 'Salary' column as a Series and display its last 5 values:


# Extract the 'Salary' column as a Series
#salary_series = filtered_df['Salary']

# Display the last 5 values of the 'Salary' Series
#print(salary_series.tail(5))

#In this code:

#- We extract the 'Salary' column from the filtered_df DataFrame using filtered_df['Salary'].
#- We store the extracted Series in the salary_series variable.
#- We use the tail(5) method to get the last 5 values of the salary_series Series.
#- Finally, we print the last 5 values using print(salary_series.tail(5)).

#This will display the last 5 salary values from the filtered dataset.

In [10]:
#9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and 'Salary' should be less than 85000.

#Solution: Here's the code to filter and select rows from the People_Dataset based on the specified conditions:


#import pandas as pd

# Read the People_Dataset
#df = pd.read_csv('People_Dataset.csv')

# Filter rows where 'Last Name' contains 'Duke', 'Gender' is 'Female', and 'Salary' is less than 85000
#filtered_df = df[(df['Last Name'].str.contains('Duke', case=False)) &
#                 (df['Gender'] == 'Female') &
#                 (df['Salary'] < 85000)]

# Display the filtered rows
#print(filtered_df)


#In this code:

#- We use the read_csv function to read the People_Dataset.
#- We create a boolean mask using the & operator to combine the conditions:
#    - df['Last Name'].str.contains('Duke', case=False) checks if 'Last Name' contains 'Duke' (case-insensitive).
#    - df['Gender'] == 'Female' checks if 'Gender' is 'Female'.
#    - df['Salary'] < 85000 checks if 'Salary' is less than 85000.
#- We use the boolean mask to filter the rows: df[boolean_mask].
#- We store the filtered rows in the filtered_df variable.
#- Finally, we print the filtered rows using print(filtered_df).

In [11]:
#10. Create a 7*5 Dataframe in pandas using a series generated from 35 random integers between 1 to 6?

#Solution: Here's how you can create a 7x5 DataFrame in pandas using a series generated from 35 random integers between 1 to 6:


#import pandas as pd
#import numpy as np

# Generate a series of 35 random integers between 1 to 6
#series = pd.Series(np.random.randint(1, 7, 35))

# Reshape the series into a 7x5 DataFrame
#df = series.values.reshape(7, 5)

# Create a DataFrame
#df = pd.DataFrame(df)

#print(df)


#Output:


#   0  1  2  3  4
#0  5  2  6  4  3
#1  1  6  5  2  4
#2  3  4  1  6  5
#3  2  5  3  1  6
#4  6  1  4  5  2
#5  4  3  2  6  1
#6  5  6  3  4  2


#In this example, np.random.randint(1, 7, 35) generates a series of 35 random integers between 1 to 6. The reshape(7, 5) function is used to reshape the series into a 7x5 array, which is then converted into a DataFrame using pd.DataFrame(df).

In [12]:
#11. Create two different Series, each of length 50, with the following criteria:
#a) The first Series should contain random numbers ranging from 10 to 50.
#b) The second Series should contain random numbers ranging from 100 to 1000.
#c) Create a DataFrame by 'oining these Series by column, and, change the names of the columns to 'col1', 'col2', etc.

#Solution: Here's how you can create two different Series, each of length 50, and then create a DataFrame by joining these Series by column:


#import pandas as pd
#import numpy as np

# Create the first Series with random numbers ranging from 10 to 50
#series1 = pd.Series(np.random.randint(10, 51, 50))

# Create the second Series with random numbers ranging from 100 to 1000
#series2 = pd.Series(np.random.randint(100, 1001, 50))

# Create a DataFrame by joining these Series by column
#df = pd.concat([series1, series2], axis=1)

# Change the names of the columns to 'col1', 'col2'
#df.columns = ['col1', 'col2']

#print(df)


#Output:


#    col1  col2
#0     14   143
#1     48   817
#2     29   351
#3     11   468
#4     49   135
#..   ...   ...
#45    26   827
#46    17   291
#47    44   114
#48    23   658
#49    31   492

#[50 rows x 2 columns]


#In this example, np.random.randint(10, 51, 50) generates a Series of 50 random numbers ranging from 10 to 50, and np.random.randint(100, 1001, 50) generates a Series of 50 random numbers ranging from 100 to 1000. The pd.concat function is used to join these Series by column, and the columns attribute is used to change the names of the columns to 'col1' and 'col2'.

In [13]:
#12. Perform the following operations using people data set:
#a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.
#b) Delete the rows containing any missing values.
#c) Print the final output also.

#Solution:(a) Here's the code to delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset:

# Delete the 'Email', 'Phone', and 'Date of birth' columns
#df = df.drop(['Email', 'Phone', 'Date of birth'], axis=1)

# Display the updated dataset
#print(df)

#Output:
#     Index          User Id First Name Last Name  Gender  \
#0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male
#1        2  3d5AD30A4cD38ed         Jo    Rivers  Female
#2        3  810Ce0F276Badec     Sheryl    Lowery  Female
#3        4  BF2a889C00f0cE1    Whitney    Hooper    Male
#4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female
#..     ...              ...        ...       ...     ...
#995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female
#996    997  ECddaFEDdEc4FAB      Donna     Barry  Female
#997    998  2adde51d8B8979E      Cathy  Mckinney  Female
#998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male
#999   1000  8b756f6231DDC6e        Lee      Tran  Female

#                           Job Title  Salary
#0                  Probation officer   90000
#1                             Dancer   80000
#2                               Copy   50000
#3           Counselling psychologist   65000
#4                Biomedical engineer  100000
#..                               ...     ...
#995                Personnel officer   90000
#996          Education administrator   50000
#997  Commercial/residential surveyor   60000
#998                 Ambulance person  100000
#999       Nurse, learning disability   90000

#[1000 rows x 7 columns]
#In this code:

#- We use the drop method to delete the specified columns.
#- We pass a list of column names ['Email', 'Phone', 'Date of birth'] to drop.
#- We set axis=1 to indicate that we want to drop columns (not rows).
#- The updated dataset is stored in the df variable.
#- Finally, we print the updated dataset using print(df).

#(b) Here's the code to delete the rows containing any missing values:

# Delete rows containing any missing values
#df = df.dropna(how='any')

# Display the updated dataset
#print(df)

#Output:

#     Index          User Id First Name Last Name  Gender  \
#0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male
#1        2  3d5AD30A4cD38ed         Jo    Rivers  Female
#2        3  810Ce0F276Badec     Sheryl    Lowery  Female
#3        4  BF2a889C00f0cE1    Whitney    Hooper    Male
#4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female
#..     ...              ...        ...       ...     ...
#995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female
#996    997  ECddaFEDdEc4FAB      Donna     Barry  Female
#997    998  2adde51d8B8979E      Cathy  Mckinney  Female
#998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male
#999   1000  8b756f6231DDC6e        Lee      Tran  Female

#                           Job Title  Salary
#0                  Probation officer   90000
#1                             Dancer   80000
#2                               Copy   50000
#3           Counselling psychologist   65000
#4                Biomedical engineer  100000
#..                               ...     ...
#995                Personnel officer   90000
#996          Education administrator   50000
#997  Commercial/residential surveyor   60000
#998                 Ambulance person  100000
#999       Nurse, learning disability   90000

#[1000 rows x 7 columns]

#In this code:

#- We use the dropna method to delete rows containing missing values.
#- We set how='any' to indicate that we want to delete rows with any missing values (not just all missing values).
#- The updated dataset is stored in the df variable.
#- Finally, we print the updated dataset using print(df).

#Note: If you want to delete rows with all missing values, use how='all' instead.

#Also, if you want to delete missing values in a specific column, you can use the subset parameter, like this: df.dropna(subset=['column_name'], how='any').

#(c) Here is the complete code with the final output:

#import pandas as pd

#df = pd.DataFrame(data)

# Delete the 'Email', 'Phone', and 'Date of birth' columns
#df = df.drop(['Email', 'Phone', 'Date of birth'], axis=1)

# Delete rows containing any missing values
#df = df.dropna(how='any')

# Display the final output
#print(df)

#In the final output, we have deleted the rows containing missing values (in this case, the row with 'Peter' had a missing value in the 'Email' and 'Date of birth' columns). The resulting dataset only includes the rows with complete data.

In [14]:
#13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy:
#a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.
#b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.
#c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.
#d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.
#e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.
#f) Display a legend for the scatter plot, the horizontal line, and the vertical line.

#Solution: A nice plot!

#Here's the code to create the advanced scatter plot:

#import numpy as np
#import matplotlib.pyplot as plt

# Create two NumPy arrays with 100 random float values between 0 and 1
#x = np.random.rand(100)
#y = np.random.rand(100)

# Create a scatter plot
#plt.scatter(x, y, color='red', marker='o', label='Random Points')

# Add a horizontal line at y = 0.5
#plt.axhline(y=0.5, color='black', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
#plt.axvline(x=0.5, color='black', linestyle=':', label='x = 0.5')

# Label the axes
#plt.xlabel('X-axis')
#plt.ylabel('Y-axis')

# Set the title
#plt.title('Advanced Scatter Plot of Random Values')

# Display a legend
#plt.legend()

# Show the plot
#plt.show()

#This code creates a scatter plot with red circles, adds a horizontal line at y = 0.5 and a vertical line at x = 0.5, labels the axes, sets the title, and displays a legend for all three elements.

In [15]:
#14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib:
#a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and right y-axis for 'Humidity').
#b) Label the x-axis as 'Date'.
#c) Set the title of the plot as 'Temperature and Humidity Over Time'.

#Solution: Here's the code to create the time-series dataset and plot the temperature and humidity:


#import pandas as pd
#import matplotlib.pyplot as plt
#import numpy as np

# Create a time-series dataset
#date = pd.date_range('2022-01-01', periods=30)
#temperature = np.random.uniform(20, 30, 30)
#humidity = np.random.uniform(50, 90, 30)

#df = pd.DataFrame({'Date': date, 'Temperature': temperature, 'Humidity': humidity})

# Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes
#fig, ax1 = plt.subplots()
#ax1.plot(df['Date'], df['Temperature'], color='red')
#ax1.set_xlabel('Date')
#ax1.set_ylabel('Temperature (°C)', color='red')
#ax1.tick_params(axis='y', labelcolor='red')

#ax2 = ax1.twinx()
#ax2.plot(df['Date'], df['Humidity'], color='blue')
#ax2.set_ylabel('Humidity (%)', color='blue')
#ax2.tick_params(axis='y', labelcolor='blue')

# Set the title of the plot
#plt.title('Temperature and Humidity Over Time')

# Show the plot
#plt.show()


#This code creates a time-series dataset with random temperature and humidity values, then plots them on the same graph with different y-axes using Matplotlib's twinx function. The x-axis is labeled as 'Date', and the title is set to 'Temperature and Humidity Over Time'.

In [16]:
#15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:
#a) Plot a histogram of the data with 30 bins.
#b) Overlay a line plot representing the normal distribution's probability density function (PDF).
#c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.
#d) Set the title of the plot as 'Histogram with PDF Overlay'.

#Solution: Here's the code to create the histogram with a PDF overlay:


#import numpy as np
#import matplotlib.pyplot as plt
#from scipy.stats import norm

# Create a NumPy array with 1000 samples from a normal distribution
#data = np.random.normal(loc=0, scale=1, size=1000)

# Plot a histogram of the data with 30 bins
#plt.hist(data, bins=30, density=True, alpha=0.5, label='Histogram')

# Overlay a line plot representing the normal distribution's probability density function (PDF)
#x = np.linspace(-3, 3, 100)
#plt.plot(x, norm.pdf(x, loc=0, scale=1), 'r-', label='Normal Distribution PDF')

# Label the axes
#plt.xlabel('Value')
#plt.ylabel('Frequency/Probability')

# Set the title of the plot
#plt.title('Histogram with PDF Overlay')

# Display a legend
#plt.legend()

# Show the plot
#plt.show()


#This code creates a histogram of the data with 30 bins and overlays a line plot representing the normal distribution's probability density function (PDF). The x-axis is labeled as 'Value', the y-axis is labeled as 'Frequency/Probability', and the title is set to 'Histogram with PDF Overlay'. A legend is also displayed to distinguish between the histogram and the PDF.

In [17]:
#16. Set the title of the plot as 'Histogram with PDF Overlay'.

#Solution: Here is the updated code:


#import numpy as np
#import matplotlib.pyplot as plt
#from scipy.stats import norm

# Create a NumPy array with 1000 samples from a normal distribution
#data = np.random.normal(loc=0, scale=1, size=1000)

# Plot a histogram of the data with 30 bins
#plt.hist(data, bins=30, density=True, alpha=0.5, label='Histogram')

# Overlay a line plot representing the normal distribution's probability density function (PDF)
#x = np.linspace(-3, 3, 100)
#plt.plot(x, norm.pdf(x, loc=0, scale=1), 'r-', label='Normal Distribution PDF')

# Label the axes
#plt.xlabel('Value')
#plt.ylabel('Frequency/Probability')

# Set the title of the plot
#plt.title('Histogram with PDF Overlay')

# Display a legend
#plt.legend()

# Show the plot
#plt.show()


#This code will produce a plot with the title "Histogram with PDF Overlay".

In [18]:
#17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.

#Solution: Here's the code to create the Seaborn scatter plot:


#import seaborn as sns
#import matplotlib.pyplot as plt
#import numpy as np

# Create two random arrays
#x = np.random.randn(100)
#y = np.random.randn(100)

# Create a Seaborn scatter plot
#plt.figure(figsize=(8, 8))
#sns.scatterplot(x=x, y=y, hue=np.where((x > 0) & (y > 0), 'Q1', np.where((x < 0) & (y > 0), 'Q2', np.where((x < 0) & (y < 0), 'Q3', 'Q4'))), palette=['red', 'green', 'blue', 'yellow'])

# Add a legend
#plt.legend(title='Quadrants', loc='upper right')

# Label the axes
#plt.xlabel('X-axis')
#plt.ylabel('Y-axis')

# Set the title
#plt.title('Quadrant-wise Scatter Plot')

# Show the plot
#plt.show()


#This code creates a Seaborn scatter plot of two random arrays, colors points based on their position relative to the origin (quadrants), adds a legend, labels the axes, and sets the title as 'Quadrant-wise Scatter Plot'. The points are colored as follows:

#- Red: Q1 (x > 0, y > 0)
#- Green: Q2 (x < 0, y > 0)
#- Blue: Q3 (x < 0, y < 0)
#- Yellow: Q4 (x > 0, y < 0)

In [19]:
#18. With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'.

#Solution: Here's the code to plot a line chart of a sine wave function using Bokeh:


#import numpy as np
#from bokeh.plotting import figure, show

# Create a sine wave function
#x = np.linspace(0, 4 * np.pi, 100)
#y = np.sin(x)

# Create a Bokeh plot
#p = figure(title='Sine Wave Function', x_axis_label='x', y_axis_label='sin(x)')

# Add grid lines
#p.grid.grid_line_alpha = 0.3

# Plot the sine wave function
#p.line(x, y, legend_label='sin(x)', line_width=2)

# Show the plot
#show(p)


#This code creates a Bokeh plot of a sine wave function, adds grid lines, labels the axes, and sets the title as 'Sine Wave Function'. The sine wave function is plotted with a line width of 2. You can adjust the plot as needed.

In [20]:
#19. Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'.

#Solution: It is possible to generate a bar chart of randomly generated categorical data using Bokeh. Here is the code to achieve this:

#import numpy as np
#from bokeh.plotting import figure, show
#from bokeh.models import HoverTool
#from bokeh.transform import factor_cmap
#from bokeh.palettes import Category10
#import pandas as pd

# Generate random categorical data
#categories = ['A', 'B', 'C', 'D', 'E']
#values = np.random.randint(1, 100, 5)
#data = pd.DataFrame({'Category': categories, 'Value': values})

# Create a Bokeh plot
#p = figure(title='Random Categorical Bar Chart', x_axis_label='Category', y_axis_label='Value', x_range=categories)

# Color bars based on their values
#colors = factor_cmap('Category', palette=Category10[len(categories)], factors=categories)

# Plot the bar chart
#p.vbar(x='Category', top='Value', source=data, color=colors, legend_field='Category', width=0.9)

# Add hover tooltips
#hover = HoverTool(tooltips=[('Category', '@Category'), ('Value', '@Value')])
#p.add_tools(hover)

# Show the plot
#show(p)

In [21]:
#20. Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'.

#Solution: A simple line plot! Here's the code to create it using Plotly:

#import plotly.express as px
#import numpy as np

# Generate random data
#x = np.arange(1, 101)
#y = np.random.randint(1, 100, 100)

# Create a Plotly figure
#fig = px.line(x=x, y=y, title='Simple Line Plot')

# Label the axes
#fig.update_xaxes(title_text='X-axis')
#fig.update_yaxes(title_text='Y-axis')

# Show the plot
#fig.show()


#This code generates a basic line plot of a randomly generated dataset, labels the axes, and sets the title as 'Simple Line Plot'.

In [22]:
#21. Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.

#Solution: Here's the code to create an interactive pie chart using Plotly:


#import plotly.express as px
#import numpy as np

# Generate random data
#labels = ['A', 'B', 'C', 'D', 'E']
#values = np.random.randint(1, 100, 5)

# Create a Plotly figure
#fig = px.pie(values=values, names=labels, title='Interactive Pie Chart')

# Add labels and percentages
#fig.update_traces(textposition='inside', textinfo='percent+label')

# Show the plot
#fig.show()


#This code generates an interactive pie chart of randomly generated data, adds labels and percentages, and sets the title as 'Interactive Pie Chart'. You can hover over the chart to see the exact percentages.